dist: trusty
sudo: required
language: python

python:
- 3.5
- 3.5-dev
- 3.6
- 3.6-dev
- 3.7-dev
- nightly

jdk:
  - openjdk7
      
before_install:
- sudo apt-get install graphviz
- sudo apt-get update -qq
- sudo apt-get install -y -qq python dh-autoreconf squashfs-tools build-essential
- cd ${TRAVIS_BUILD_DIR}

install:
- pip install --upgrade setuptools
- pip install coveralls pytest==5.2.0 pytest-runner pycodestyle
- pip install .
- docker build ${TRAVIS_BUILD_DIR}/spot/example/centos7/subject1/ -t spot_centos7_latest
- docker build ${TRAVIS_BUILD_DIR}/spot/example/centos6/subject1/ -t spot_centos6_latest
script:
- pycodestyle --max-line-length=80 *.py */*.py
- coverage run --source spot setup.py pytest

after_success:
- coveralls

deploy:
